import numpy as np
import matplotlib.pyplot as plt

# Physical Constants
R = 2.0  # Radius of the disk in meters
epsilon_0 = 8.854e-12  
V0 = 1.0   # Fixed potential of the disk
k_coulomb = 1 / (4 * np.pi * epsilon_0)

# To integrate numerically, dividing the disk into a grid of square cells
N_grid = 120   # Number of cells per side of the square (which contains the disk)
L_box = 2 * R 
dx = L_box / N_grid
area = dx**2  # Area of each cell

# Create Squares grid
x = np.linspace(-L_box/2, L_box/2, N_grid)
y = np.linspace(-L_box/2, L_box/2, N_grid)
X, Y = np.meshgrid(x, y)

# Mask: select only points within the disk
R_dist = np.sqrt(X**2 + Y**2)
mask = R_dist < R  
X_disco = X[mask]
Y_disco = Y[mask]
N = len(X_disco) # Number of effective unknowns

print(f"Solving for {N} elements...")

# Calculate distances between squares using the distance matrix
x_vec = X_disco[:, np.newaxis] # Column vector
y_vec = Y_disco[:, np.newaxis]
dist_sq = (x_vec - x_vec.T)**2 + (y_vec - y_vec.T)**2 
dist_matrix = np.sqrt(dist_sq) # Distance matrix r_ij

# Initialize M, matrix of known terms
M = np.zeros((N, N))


# For off-diagonal terms of A (i != j) consider the charge as point-like concentrated at the center of the square
M = k_coulomb * area / dist_matrix

# For diagonal terms (i == j) the potential can be calculated as generated by a charge uniformly distributed at the center of the square
# If the square has side a, the potential at the center is given by:
# V(0, 0) = (sigma*/(4*pi*epsilon_0)) * (4*a*ln(1 + sqrt(2)))
np.fill_diagonal(M, k_coulomb * (4 * np.log(1 + np.sqrt(2))) * dx)


# To estimate the charge distribution, setting the potential of each square to V0 (uniform because conductor is in equilibrium)
V_vec = np.full(N, V0)

# Solve for the total charges q on each pixel
Sigma = np.linalg.solve(M, V_vec)

# Construction of the 2D plot
sigma_grid = np.full((N_grid, N_grid), np.nan)
sigma_grid[mask] = Sigma

# Total Charge Calculation
Q_tot = np.sum(Sigma)*(dx**2)

print(f"Calculated Total Charge: {Q_tot:.4e} C")

# Plot
plt.figure(figsize=(10, 8))
plt.rc('text', usetex=True)
plt.imshow(sigma_grid, origin='lower', extent=[-L_box/2, L_box/2, -L_box/2, L_box/2], cmap='inferno')
plt.colorbar(label=r'Charge density $\sigma$ [C/m$^2$]')
plt.title(f'Charge Distribution on Conducting Disk at Equilibrium\nQ_calc = {Q_tot:.2e} C')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.show()

# Plot sigma(r)
# Taking points close to y=0
radial_cells_mask = (np.abs(Y_disco) < dx) & (X_disco > 0)
r = X_disco[radial_cells_mask]
sigma_radial = Sigma[radial_cells_mask]
plt.figure(figsize=(8, 4))
plt.scatter(r, sigma_radial, s=10, c='red')
plt.title("Charge as a function of radius $r$")
plt.xlabel("r [m]")
plt.ylabel(r"$\sigma$ [C/m$^2$]")
plt.grid(True, alpha=0.3)
plt.show()